name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 3 minutes (UTC)
  workflow_dispatch:        # Optional: allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: |
          echo "Pinging Render..."
           curl -m 60 -w "%{http_code}" https://satellite-backend-v1.onrender.com/actuator/health || true
